weather:
  # database_url: "postgresql://postgres:Humanway=1974@127.0.0.1:5432/location_me_db"
  database_url: "postgresql://postgres:Humanway=1974@location_me_db:5432/location_me_db"
  # 都道府県庁所在地
  locations:
    - name: "福岡県"
      code: "101"
      latitude: 33.606389
      longitude: 130.417968
    - name: "佐賀県"
      code: "201"
      latitude: 33.249351
      longitude: 130.298792
    - name: "長崎県"
      code: "301"
      latitude: 32.750040
      longitude: 129.867251
    - name: "熊本県"
      code: "401"
      latitude: 32.789800
      longitude: 130.741584
    - name: "大分県"
      code: "501"
      latitude: 33.238130
      longitude: 131.612645
    - name: "宮崎県"
      code: "601"
      latitude: 31.911034
      longitude: 131.423887
    - name: "鹿児島県"
      code: "701"
      latitude: 31.560171
      longitude: 130.558025
    - name: "沖縄県"
      code: "801"
      latitude: 26.212445
      longitude: 127.680922
